Make Header / Navbar follow the same width as body
cfoellmann/github-wide pull request #7
Opened 2017-07-25 23:03 UTC by hernandev

2017-07-25 23:10 UTC, hernandev commented
Sorry @mike-koch did not saw you already sent #6 to fix this, the code is slightly different but the result is the same.

2017-08-24 13:34 UTC, nickcampbell18 commented
Just came here to find this, anything I can help with to get this merged?

2017-08-24 13:37 UTC, nickcampbell18 commented on github-wide.css
> +  max-width: 80% !important;
I think you can also do this with `max-width: none!important`.

2017-08-24 16:21 UTC, cfoellmann requested changes
Please change
https://github.com/hernandev/github-wide/blob/05379c95020a002480067791b6a67d95d7fba09a/github-wide.css#L6
to `max-width: none !important;`

2017-08-24 16:21 UTC, cfoellmann commented on github-wide.css
> +  max-width: 80% !important;
80% is not "full-screen" for me.
Why not 100% to use the full width?

2017-08-24 16:22 UTC, cfoellmann commented
@nickcampbell18 I hope @hernandev will see my change request soon. Otherwise I will merge in 2 or 3 days.

2017-09-05 10:52 UTC, merged